dist: xenial
language: go
go:
    - 1.13.x


install:
    - mkdir $HOME/src
    - cd $HOME/src
    - git clone https://github.com/gohugoio/hugo.git
    - cd hugo
    - go install

before_script:
    - rm -rf public 2> /dev/null

script:
    - hugo
    - echo "$CNAME_URL" > public/CNAME

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  verbose: true
  keep-history: false
  local-dir: public
  on:
    branch: master
